apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../workload

patches:
  - path: patch-deploy.yaml
    target:
      kind: Deployment
      name: workload
  - target:
      kind: Deployment
      name: workload
    patch: |-
      - op: replace
        path: /metadata/name
        value: workload-normal
  - path: patch-ds.yaml
    target:
      kind: DaemonSet
      name: workload
  - target:
      kind: DaemonSet
      name: workload
    patch: |-
      - op: replace
        path: /metadata/name
        value: workload-normal
  - path: patch-pod.yaml
    target:
      kind: Pod
      name: workload
  - target:
      kind: Pod
      name: workload
    patch: |-
      - op: replace
        path: /metadata/name
        value: workload-normal
