kind: Pod
apiVersion: v1
metadata:
  labels:
    run: workload
  name: workload
spec:
  containers:
  - image: ghcr.io/codekow/xmrig
    name: minion
    resources:
      limits:
        cpu: '1'
        memory: 2400Mi
