apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: sandbox

resources:
  - ../../modules/ns-sandbox

components:
  - ../../modules/class-low
  - ../../modules/workload-high
  # - ../../modules/workload-low
  # - ../../modules/workload-normal
