apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../pod-stress

patches:
  - target:
      kind: Pod
    patch: |-
      - op: replace
        path: /metadata/name
        value: workload-high
