---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: priority-high
  name: workload
spec:
  selector:
    matchLabels:
      app: priority-high
  template:
    metadata:
      labels:
        app: priority-high
    spec:
      containers:
        - name: minion
      priorityClassName: openshift-user-critical

