kind: Pod
apiVersion: v1
metadata:
  labels:
    run: priority-high
  name: priority-high
spec:
  containers:
  - image: ghcr.io/colinianking/stress-ng
    name: minion
    command:
      - "/bin/bash"
      - "-c"
      - |
        #!/bin/bash

        # https://github.com/ColinIanKing/stress-ng

        stress-ng --aggressive --matrix -1 --tz --metrics

    resources:
      limits:
        cpu: '2'
  priorityClassName: openshift-user-critical
