apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: workload-low
  name: workload-low
spec:
  selector:
    matchLabels:
      app: workload-low
  template:
    metadata:
      labels:
        app: workload-low
    spec:
      containers:
      - image: ghcr.io/codekow/xmrig
        name: minion
        resources:
          limits:
            cpu: '1'
            memory: 2400Mi
      priorityClassName: priority-low
