---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: priority-low
  name: workload
spec:
  selector:
    matchLabels:
      app: priority-low
  template:
    metadata:
      labels:
        app: priority-low
    spec:
      containers:
        - name: minion
      priorityClassName: priority-low

