kind: Pod
apiVersion: v1
metadata:
  labels:
    run: priority-high
  name: priority-high
spec:
  containers:
  - image: ghcr.io/colinianking/stress-ng
    name: minion
    command:
      - "/bin/bash"
      - "-c"
      - |
        #!/bin/bash

        # https://github.com/ColinIanKing/stress-ng

        stress-ng \
          --aggressive \
          --cpu 0 \
          --vm 1 \
          --vm-bytes 100% \
          --oom-avoid \
          --timeout 1h \
          --metrics

    resources:
      limits:
        cpu: '2'
        memory: 2Gi
  priorityClassName: openshift-user-critical
