---
apiVersion: scheduling.k8s.io/v1
description: This priority class should be used for very low priority workloads (nice -20)
kind: PriorityClass
metadata:
  name: priority-low
preemptionPolicy: PreemptLowerPriority
value: -1000000000
